apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uwq0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-uwq0@sha256:4bf10fc1c7f100e1b3c6fb474a481bd176d4c389034fd0a13c7ac3c6f7f1885a
        name: my-nodejs
        resources: {}
status: {}
